### ISSUE TITLE
Airplane built!

### ISSUE THREAD

**Issue by aguileraGit** [daneallen/avBadge_2020#4]
Awesome PCB! I just finished soldering it. I fear I'm going to lose it to my children rather quickly.

I believe there is an issue with your ground planes. Using an unpopulated PCB, if you place your DMM on J4-GND and the other on U1 GND, you'll notice it's open. You can view the same if you place the DMM between the GND pins on J2. This caused me quite some issue trying to get it programmed. The issue is solved by soldering J2. That's enough to bridge the two ground planes together.

Also, U1 doesn't have a dot to indicate Pin 1.

**Comment by daneallen** [comment]
Yes.. you are correct. The short on J2 was accidental, but then I kinda liked how the J2 part was required to complete the build.. in much the same way everything in aviation is used as much as possible. It does make for tricky troubleshooting though. The pin for U1 is indicated by the slightly longer line, adding a dot would be a good idea.

I'm glad you liked the build and thanks for the feedback!
